# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

matrix:
  include:
    - os: osx
      osx_image: xcode10.2
      sudo: required
      language: objective-c
      podfile: Example/Podfile
      env: TEST_DESTINATION="OS=12.2,name=iPhone X"
      script:
        - set -o pipefail && xcodebuild test -workspace Example/BirdBush.xcworkspace -scheme BirdBush-Example -destination "$TEST_DESTINATION" | xcpretty
